apiVersion: v1
kind: Pod
metadata:
  name: someName
  namespace: someNamespace
spec:
  containers:
    - name: someContainer
      image: someImage
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/data"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: prod/service/token
        items:
          - key: MONGO_CONFIGMAP_USER
            path: DATABASE_USER
          - key: MONGO_CONFIGMAP_PASSWORD
            path: DATABASE_PASSWORD
          - key: MONGO_DATABASE_URL
            path: DATABASE_URL