apiVersion: apps/v1
kind: Deployment
metadata:
  name: odin-coordinator-payment
  labels:
    app: odin-coordinator-payment
spec:
  selector:
    matchLabels:
      app: odin-coordinator-payment
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: odin-coordinator-payment
        #octopusexport: OctopusExport
    spec:
      volumes:
        - name: nfs-pv
          secret:
            secretName: API_TOKEN
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: aws-secrets
      containers:
        - name: odin-coordinator-payment
          image: 589696708747.dkr.ecr.sa-east-1.amazonaws.com/odin-coordinator-payment:main-69e20488-1640701468
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: SECRET_TOKEN
          volumeMounts:
            - name: nfs-pv
              mountPath: /mnt/api-token
              subPath: ''
